<?php

namespace ContainerDy4luQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KN4nawW.App\Entity\Series' shared service.
     *
     * @return \App\Entity\Series
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KN4nawW": it needs an instance of "App\\Entity\\Series" but this type has been excluded in "config/services.yaml".');
    }
}
