<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUcEKYrX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUcEKYrX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUcEKYrX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUcEKYrX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUcEKYrX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UcEKYrX',
    'container.build_id' => 'f47baabb',
    'container.build_time' => 1670947337,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUcEKYrX');
