<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYeNtJ5U\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYeNtJ5U/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYeNtJ5U.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYeNtJ5U\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYeNtJ5U\App_KernelDevDebugContainer([
    'container.build_hash' => 'YeNtJ5U',
    'container.build_id' => 'a4ab76eb',
    'container.build_time' => 1671029246,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYeNtJ5U');
