<?php

namespace ContainerYeNtJ5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_InbeGToService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.InbeGTo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.InbeGTo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CountryController::delete' => ['privates', '.service_locator.kYo2yu0', 'get_ServiceLocator_KYo2yu0Service', true],
            'App\\Controller\\CountryController::edit' => ['privates', '.service_locator.kYo2yu0', 'get_ServiceLocator_KYo2yu0Service', true],
            'App\\Controller\\CountryController::index' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\CountryController::new' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\CountryController::show' => ['privates', '.service_locator.JBzDJl7', 'get_ServiceLocator_JBzDJl7Service', true],
            'App\\Controller\\MessageController::delete' => ['privates', '.service_locator.UoAUkAt', 'get_ServiceLocator_UoAUkAtService', true],
            'App\\Controller\\MessageController::edit' => ['privates', '.service_locator.UoAUkAt', 'get_ServiceLocator_UoAUkAtService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController::new' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController::show' => ['privates', '.service_locator.MjFFzS6', 'get_ServiceLocator_MjFFzS6Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.ZCEnAlM', 'get_ServiceLocator_ZCEnAlMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.bw8tvv2', 'get_ServiceLocator_Bw8tvv2Service', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.RdVbGrJ', 'get_ServiceLocator_RdVbGrJService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\CountryController:delete' => ['privates', '.service_locator.kYo2yu0', 'get_ServiceLocator_KYo2yu0Service', true],
            'App\\Controller\\CountryController:edit' => ['privates', '.service_locator.kYo2yu0', 'get_ServiceLocator_KYo2yu0Service', true],
            'App\\Controller\\CountryController:index' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\CountryController:new' => ['privates', '.service_locator.7HgipzG', 'get_ServiceLocator_7HgipzGService', true],
            'App\\Controller\\CountryController:show' => ['privates', '.service_locator.JBzDJl7', 'get_ServiceLocator_JBzDJl7Service', true],
            'App\\Controller\\MessageController:delete' => ['privates', '.service_locator.UoAUkAt', 'get_ServiceLocator_UoAUkAtService', true],
            'App\\Controller\\MessageController:edit' => ['privates', '.service_locator.UoAUkAt', 'get_ServiceLocator_UoAUkAtService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController:new' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController:show' => ['privates', '.service_locator.MjFFzS6', 'get_ServiceLocator_MjFFzS6Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.ZCEnAlM', 'get_ServiceLocator_ZCEnAlMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\CountryController::delete' => '?',
            'App\\Controller\\CountryController::edit' => '?',
            'App\\Controller\\CountryController::index' => '?',
            'App\\Controller\\CountryController::new' => '?',
            'App\\Controller\\CountryController::show' => '?',
            'App\\Controller\\MessageController::delete' => '?',
            'App\\Controller\\MessageController::edit' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::new' => '?',
            'App\\Controller\\MessageController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\CountryController:delete' => '?',
            'App\\Controller\\CountryController:edit' => '?',
            'App\\Controller\\CountryController:index' => '?',
            'App\\Controller\\CountryController:new' => '?',
            'App\\Controller\\CountryController:show' => '?',
            'App\\Controller\\MessageController:delete' => '?',
            'App\\Controller\\MessageController:edit' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:new' => '?',
            'App\\Controller\\MessageController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
