<?php

namespace ContainerYeNtJ5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KYo2yu0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kYo2yu0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kYo2yu0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'country' => ['privates', '.errored..service_locator.kYo2yu0.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.kYo2yu0": it references class "App\\Entity\\Country" but no such service exists.'],
            'countryRepository' => ['privates', 'App\\Repository\\CountryRepository', 'getCountryRepositoryService', true],
        ], [
            'country' => 'App\\Entity\\Country',
            'countryRepository' => 'App\\Repository\\CountryRepository',
        ]);
    }
}
