<?php

namespace ContainerYeNtJ5U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MaudController' shared autowired service.
     *
     * @return \App\Controller\MaudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MaudController.php';

        $container->services['App\\Controller\\MaudController'] = $instance = new \App\Controller\MaudController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\MaudController', $container));

        return $instance;
    }
}
