<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDy4luQA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDy4luQA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDy4luQA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDy4luQA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDy4luQA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dy4luQA',
    'container.build_id' => 'e067e971',
    'container.build_time' => 1671036577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDy4luQA');
