<?php

namespace ContainerNNvvkxf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KN4nawWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KN4nawW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KN4nawW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'series' => ['privates', '.errored..service_locator.KN4nawW.App\\Entity\\Series', NULL, 'Cannot autowire service ".service_locator.KN4nawW": it needs an instance of "App\\Entity\\Series" but this type has been excluded in "config/services.yaml".'],
        ], [
            'series' => 'App\\Entity\\Series',
        ]);
    }
}
