<?php

namespace ContainerQ1tuiaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCountry2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kYo2yu0.App\Entity\Country' shared service.
     *
     * @return \App\Entity\Country
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kYo2yu0": it references class "App\\Entity\\Country" but no such service exists.');
    }
}
