<?php

namespace ContainerQ1tuiaV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UoAUkAt.App\Entity\Message' shared service.
     *
     * @return \App\Entity\Message
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UoAUkAt": it references class "App\\Entity\\Message" but no such service exists.');
    }
}
